name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Extract certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLICATION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.APPLICATION_CERTIFICATE_P12_PASSWORD }}

      - name: Build and sign macOS prebuild
        run: |
          npx prebuild --backend node-gyp --target 20.3.0 --arch x64 --platform darwin --strip
          codesign --sign "Developer ID Application: Your Name ${{var.TEAM_ID}}" --timestamp --options runtime ./prebuilds/darwin-x64/node_printer.node

      - name: Upload prebuild to GitHub release
        run: npx prebuild --upload-all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- --strip --arch ia32
          npm run prebuild -- --strip --arch x64
          npm run prebuild -- --upload-all
