name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Get Version
        id: get-version
        run: |
          echo "console.log(require('./package.json').version);" > get-version.js
          echo "version=$(node get-version.js)-pr${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Extract certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLICATION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.APPLICATION_CERTIFICATE_P12_PASSWORD }}

      - name: Build and sign macOS prebuild
        run: |
          npx prebuild --backend node-gyp --target 20.3.0 --arch x64 --platform darwin --strip
          ls -la prebuilds/darwin-x64/ || echo "Directory not found"
          codesign --sign "${{ vars.TEAM_ID }}" --timestamp --options runtime prebuilds/darwin-x64/node_printer.node

      - name: Create GitHub Release if it doesn't exist
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          draft: true
          files: prebuilds/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload prebuild to GitHub release
        run: npx prebuild --upload -u ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm i

      - name: Get Version
        id: get-version
        run: |
          echo "console.log(require('./package.json').version);" > get-version.js
          echo "version=$(node get-version.js)-pr${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release if it doesn't exist
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prebuild Windows binaries
        run: |
          # Build x64 version with explicit path
          npx prebuild --backend node-gyp --target 20.3.0 --arch x64 --platform win32 --strip
          
          # Build ia32 version with explicit path
          npx prebuild --backend node-gyp --target 20.3.0 --arch ia32 --platform win32 --strip
          
          # List the directories to verify
          dir prebuilds
          dir prebuilds\win32-x64 || echo "x64 directory not found"
          dir prebuilds\win32-ia32 || echo "ia32 directory not found"

      - name: Upload prebuilds to GitHub release
        run: npx prebuild --upload-all -u ${{ secrets.GITHUB_TOKEN }}
